# Required
version: 2

# Image to use
build:
  os: ubuntu-22.04
  image: testing
  tools:
    python: "3.11"

sphinx:
  configuration: docs/source/conf.py

# Configuration
python:
  install:
    - requirements: docs/requirements.txt
